# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='encrypted_pw',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='user',
            name='salt',
        ),
    ]
