# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-05-30 22:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logReg', '0002_auto_20170530_2130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='hashed_pw',
        ),
    ]
